import { proxy } from 'valtio'

const state = proxy({
  st: {
    current: null,
    currentEstado: '#feffd4',
    currentModel:'json_serialized',
    items: {
      GumsMaterial:undefined,
      distal11:undefined,
      distal12:undefined,
      distal13:undefined,
      distal14:undefined,
      distal15:undefined,
      distal16:undefined,
      distal17:undefined,
      distal18:undefined,
      distal21:undefined,
      distal22:undefined,
      distal23:undefined,
      distal24:undefined,
      distal25:undefined,
      distal26:undefined,
      distal27:undefined,
      distal28:undefined,
      distal31:undefined,
      distal32:undefined,
      distal33:undefined,
      distal34:undefined,
      distal35:undefined,
      distal36:undefined,
      distal37:undefined,
      distal38:undefined,
      distal41:undefined,
      distal42:undefined,
      distal43:undefined,
      distal44:undefined,
      distal45:undefined,
      distal46:undefined,
      distal47:undefined,
      distal48:undefined,
      incisal11:undefined,
      incisal12:undefined,
      incisal13:undefined,
      incisal21:undefined,
      incisal22:undefined,
      incisal23:undefined,
      incisal31:undefined,
      incisal32:undefined,
      incisal33:undefined,
      incisal41:undefined,
      incisal42:undefined,
      incisal43:undefined,
      lingual31:undefined,
      lingual32:undefined,
      lingual33:undefined,
      lingual34:undefined,
      lingual35:undefined,
      lingual36:undefined,
      lingual37:undefined,
      lingual38:undefined,
      lingual41:undefined,
      lingual42:undefined,
      lingual43:undefined,
      lingual44:undefined,
      lingual45:undefined,
      lingual46:undefined,
      lingual47:undefined,
      lingual48:undefined,
      mesial11:undefined,
      mesial12:undefined,
      mesial13:undefined,
      mesial14:undefined,
      mesial15:undefined,
      mesial16:undefined,
      mesial17:undefined,
      mesial18:undefined,
      mesial21:undefined,
      mesial22:undefined,
      mesial23:undefined,
      mesial24:undefined,
      mesial25:undefined,
      mesial26:undefined,
      mesial27:undefined,
      mesial28:undefined,
      mesial31:undefined,
      mesial32:undefined,
      mesial33:undefined,
      mesial34:undefined,
      mesial35:undefined,
      mesial36:undefined,
      mesial37:undefined,
      mesial38:undefined,
      mesial41:undefined,
      mesial42:undefined,
      mesial43:undefined,
      mesial44:undefined,
      mesial45:undefined,
      mesial46:undefined,
      mesial47:undefined,
      mesial48:undefined,
      oclusal48:undefined,
      oclusal14:undefined,
      oclusal15:undefined,
      oclusal16:undefined,
      oclusal17:undefined,
      oclusal18:undefined,
      oclusal24:undefined,
      oclusal25:undefined,
      oclusal26:undefined,
      oclusal27:undefined,
      oclusal28:undefined,
      oclusal34:undefined,
      oclusal35:undefined,
      oclusal36:undefined,
      oclusal37:undefined,
      oclusal38:undefined,
      oclusal44:undefined,
      oclusal45:undefined,
      oclusal46:undefined,
      oclusal47:undefined,
      palatino11:undefined,
      palatino12:undefined,
      palatino13:undefined,
      palatino14:undefined,
      palatino15:undefined,
      palatino16:undefined,
      palatino17:undefined,
      palatino18:undefined,
      palatino21:undefined,
      palatino22:undefined,
      palatino23:undefined,
      palatino24:undefined,
      palatino25:undefined,
      palatino26:undefined,
      palatino27:undefined,
      palatino28:undefined,
      tongue:undefined,
      tooth:undefined,
      "tooth.001":undefined,
      vestibular11:undefined,
      vestibular12:undefined,
      vestibular13:undefined,
      vestibular14:undefined,
      vestibular15:undefined,
      vestibular16:undefined,
      vestibular17:undefined,
      vestibular18:undefined,
      vestibular21:undefined,
      vestibular22:undefined,
      vestibular23:undefined,
      vestibular24:undefined,
      vestibular25:undefined,
      vestibular26:undefined,
      vestibular27:undefined,
      vestibular28:undefined,
      vestibular31:undefined,
      vestibular32:undefined,
      vestibular33:undefined,
      vestibular34:undefined,
      vestibular35:undefined,
      vestibular36:undefined,
      vestibular37:undefined,
      vestibular38:undefined,
      vestibular41:undefined,
      vestibular42:undefined,
      vestibular43:undefined,
      vestibular44:undefined,
      vestibular45:undefined,
      vestibular46:undefined,
      vestibular47:undefined,
      vestibular48:undefined,
    },
    itemskid: {
      GumsMaterial:undefined,
      distal51:undefined,
      distal52:undefined,
      distal53:undefined,
      distal54:undefined,
      distal55:undefined,
      distal61:undefined,
      distal62:undefined,
      distal63:undefined,
      distal64:undefined,
      distal65:undefined,
      distal71:undefined,
      distal72:undefined,
      distal73:undefined,
      distal74:undefined,
      distal75:undefined,
      distal81:undefined,
      distal82:undefined,
      distal83:undefined,
      distal84:undefined,
      distal85:undefined,
      incisal51:undefined,
      incisal52:undefined,
      incisal53:undefined,
      incisal61:undefined,
      incisal62:undefined,
      incisal63:undefined,
      incisal71:undefined,
      incisal72:undefined,
      incisal73:undefined,
      incisal81:undefined,
      incisal82:undefined,
      incisal83:undefined,
      lingual71:undefined,
      lingual72:undefined,
      lingual73:undefined,
      lingual74:undefined,
      lingual75:undefined,
      lingual81:undefined,
      lingual82:undefined,
      lingual83:undefined,
      lingual84:undefined,
      lingual85:undefined,
      mesial51:undefined,
      mesial52:undefined,
      mesial53:undefined,
      mesial54:undefined,
      mesial55:undefined,
      mesial61:undefined,
      mesial62:undefined,
      mesial63:undefined,
      mesial64:undefined,
      mesial65:undefined,
      mesial71:undefined,
      mesial72:undefined,
      mesial73:undefined,
      mesial74:undefined,
      mesial75:undefined,
      mesial81:undefined,
      mesial82:undefined,
      mesial83:undefined,
      mesial84:undefined,
      mesial85:undefined,
      oclusal:undefined,
      oclusal54:undefined,
      oclusal55:undefined,
      oclusal64:undefined,
      oclusal65:undefined,
      oclusal74:undefined,
      oclusal75:undefined,
      oclusal84:undefined,
      oclusal85:undefined,
      palatino51:undefined,
      palatino52:undefined,
      palatino53:undefined,
      palatino54:undefined,
      palatino55:undefined,
      palatino61:undefined,
      palatino62:undefined,
      palatino63:undefined,
      palatino64:undefined,
      palatino65:undefined,
      tongue:undefined,
      tooth:undefined,
      "tooth.001":undefined,
      vestibular51:undefined,
      vestibular52:undefined,
      vestibular53:undefined,
      vestibular54:undefined,
      vestibular55:undefined,
      vestibular61:undefined,
      vestibular62:undefined,
      vestibular63:undefined,
      vestibular64:undefined,
      vestibular65:undefined,
      vestibular71:undefined,
      vestibular72:undefined,
      vestibular73:undefined,
      vestibular74:undefined,
      vestibular75:undefined,
      vestibular81:undefined,
      vestibular82:undefined,
      vestibular83:undefined,
      vestibular84:undefined,
      vestibular85:undefined,
    },
  },
  caras: [
    { value: 'oclusal', label: 'Oclusal' },
    { value: 'vestibular', label: 'Vestibular' },
    { value: 'incisal', label: 'Incisal' },
    { value: 'palatino', label: 'Palatino' },
    { value: 'mesial', label: 'Mesial' },
    { value: 'distal', label: 'Distal' },
  ],
  dientes: [
    { value: '11', label: 'Incisivo Central Superior Izquierdo 11' },
    { value: '12', label: 'Incisivo Lateral Superior Izquierdo 12' },
    { value: '13', label: 'Canino Superior Izquierdo 13' },
    { value: '14', label: 'Primer Premolar Superior Izquierdo 14' },
    { value: '15', label: 'Segundo Premolar Superior Izquierdo 15' },
    { value: '16', label: 'Primer Molar Superior Izquierdo 16' },
    { value: '17', label: 'Segundo Molar Superior Izquierdo 17' },
    { value: '18', label: 'Tercer Molar Superior Izquierdo 18' },
    { value: '21', label: 'Incisivo Central Superior Derecho 21' },
    { value: '22', label: 'Incisivo Lateral Superior Derecho 22' },
    { value: '23', label: 'Canino Superior Derecho 23' },
    { value: '24', label: 'Primer Premolar Superior Derecho 24' },
    { value: '25', label: 'Segundo Premolar Superior Derecho 25' },
    { value: '26', label: 'Primer Molar Superior Derecho 26' },
    { value: '27', label: 'Segundo Molar Superior Derecho 27' },
    { value: '28', label: 'Tercer Molar Superior Derecho 28' },
    { value: '31', label: 'Incisivo Central Inferior Izquierdo 31' },
    { value: '32', label: 'Incisivo Lateral Inferior Izquierdo 32' },
    { value: '33', label: 'Canino Inferior Izquierdo 33' },
    { value: '34', label: 'Primer Premolar Inferior Izquierdo 34' },
    { value: '35', label: 'Segundo Premolar Inferior Izquierdo 35' },
    { value: '36', label: 'Primer Molar Inferior Izquierdo 36' },
    { value: '37', label: 'Segundo Molar Inferior Izquierdo 37' },
    { value: '38', label: 'Tercer Molar Inferior Izquierdo 38' },
    { value: '41', label: 'Incisivo Central Inferior Derecho 41' },
    { value: '42', label: 'Incisivo Lateral Inferior Derecho 42' },
    { value: '43', label: 'Canino Inferior Derecho 43' },
    { value: '44', label: 'Primer Premolar Inferior Derecho 44' },
    { value: '45', label: 'Segundo Premolar Inferior Derecho 45' },
    { value: '46', label: 'Primer Molar Inferior Derecho 46' },
    { value: '47', label: 'Segundo Molar Inferior Derecho 47' },
    { value: '48', label: 'Tercer Molar Inferior Derecho 48' },
  ],
  dienteskid: [
    { value: '51', label: 'Incisivo Central Superior Izquierdo 51' },
    { value: '52', label: 'Incisivo Lateral Superior Izquierdo 52' },
    { value: '53', label: 'Canino Superior Izquierdo 53' },
    { value: '54', label: 'Primer Premolar Superior Izquierdo 54' },
    { value: '55', label: 'Segundo Premolar Superior Izquierdo 55' },
    { value: '61', label: 'Incisivo Central Superior Derecho 61' },
    { value: '62', label: 'Incisivo Lateral Superior Derecho 62' },
    { value: '63', label: 'Canino Superior Derecho 63' },
    { value: '64', label: 'Primer Premolar Superior Derecho 64' },
    { value: '65', label: 'Segundo Premolar Superior Derecho 65' },
    { value: '71', label: 'Incisivo Central Inferior Izquierdo 71' },
    { value: '72', label: 'Incisivo Lateral Inferior Izquierdo 72' },
    { value: '73', label: 'Canino Inferior Izquierdo 73' },
    { value: '74', label: 'Primer Premolar Inferior Izquierdo 74' },
    { value: '75', label: 'Segundo Premolar Inferior Izquierdo 75' },
    { value: '81', label: 'Incisivo Central Inferior Derecho 81' },
    { value: '82', label: 'Incisivo Lateral Inferior Derecho 82' },
    { value: '83', label: 'Canino Inferior Derecho 83' },
    { value: '84', label: 'Primer Premolar Inferior Derecho 84' },
    { value: '85', label: 'Segundo Premolar Inferior Derecho 85' },
  ],
  estado: [
    { value: "#000000", label: 'caries' },
    { value: "#fff633", label: 'corona' },
    { value: "0", label: 'ausente' },
    { value: "#feffd4", label: 'sano' },

  ]
})



export { state }
