import { proxy } from 'valtio'

const state = proxy({
  st:{
  current: null,
  items: {
    GumsMaterial: undefined,
    distal11: undefined,
    distal12: undefined,
    distal13: undefined,
    distal14: undefined,
    distal15: undefined,
    distal16: undefined,
    distal17: undefined,
    distal18: undefined,
    distal21: undefined,
    distal22: undefined,
    distal23: undefined,
    distal24: undefined,
    distal25: undefined,
    distal26: undefined,
    distal27: undefined,
    distal28: undefined,
    distal31: undefined,
    distal32: undefined,
    distal33: undefined,
    distal34: undefined,
    distal35: undefined,
    distal36: undefined,
    distal37: undefined,
    distal38: undefined,
    distal41: undefined,
    distal42: undefined,
    distal43: undefined,
    distal44: undefined,
    distal45: undefined,
    distal46: undefined,
    distal47: undefined,
    distal48: undefined,
    incisal11: undefined,
    incisal12: undefined,
    incisal13: undefined,
    incisal21: undefined,
    incisal22: undefined,
    incisal23: undefined,
    incisal31: undefined,
    incisal32: undefined,
    incisal33: undefined,
    incisal41: undefined,
    incisal42: undefined,
    incisal43: undefined,
    lingual31: undefined,
    lingual32: undefined,
    lingual33: undefined,
    lingual34: undefined,
    lingual35: undefined,
    lingual36: undefined,
    lingual37: undefined,
    lingual38: undefined,
    lingual41: undefined,
    lingual42: undefined,
    lingual43: undefined,
    lingual44: undefined,
    lingual45: undefined,
    lingual46: undefined,
    lingual47: undefined,
    lingual48: undefined,
    mesial11: undefined,
    mesial12: undefined,
    mesial13: undefined,
    mesial14: undefined,
    mesial15: undefined,
    mesial16: undefined,
    mesial17: undefined,
    mesial18: undefined,
    mesial21: undefined,
    mesial22: undefined,
    mesial23: undefined,
    mesial24: undefined,
    mesial25: undefined,
    mesial26: undefined,
    mesial27: undefined,
    mesial28: undefined,
    mesial31: undefined,
    mesial32: undefined,
    mesial33: undefined,
    mesial34: undefined,
    mesial35: undefined,
    mesial36: undefined,
    mesial37: undefined,
    mesial38: undefined,
    mesial41: undefined,
    mesial42: undefined,
    mesial43: undefined,
    mesial44: undefined,
    mesial45: undefined,
    mesial46: undefined,
    mesial47: undefined,
    mesial48: undefined,
    oclusal: undefined,
    oclusal14: undefined,
    oclusal15: undefined,
    oclusal16: undefined,
    oclusal17: undefined,
    oclusal18: undefined,
    oclusal24: undefined,
    oclusal25: undefined,
    oclusal26: undefined,
    oclusal27: undefined,
    oclusal28: undefined,
    oclusal34: undefined,
    oclusal35: undefined,
    oclusal36: undefined,
    oclusal37: undefined,
    oclusal38: undefined,
    oclusal44: undefined,
    oclusal45: undefined,
    oclusal46: undefined,
    oclusal47: undefined,
    palatino11: undefined,
    palatino12: undefined,
    palatino13: undefined,
    palatino14: undefined,
    palatino15: undefined,
    palatino16: undefined,
    palatino17: undefined,
    palatino18: undefined,
    palatino21: undefined,
    palatino22: undefined,
    palatino23: undefined,
    palatino24: undefined,
    palatino25: undefined,
    palatino26: undefined,
    palatino27: undefined,
    palatino28: undefined,
    tongue: undefined,
    tooth: undefined,
    "tooth.001": undefined,
    vestibular11: undefined,
    vestibular12: undefined,
    vestibular13: undefined,
    vestibular14: undefined,
    vestibular15: undefined,
    vestibular16: undefined,
    vestibular17: undefined,
    vestibular18: undefined,
    vestibular21: undefined,
    vestibular22: undefined,
    vestibular23: undefined,
    vestibular24: undefined,
    vestibular25: undefined,
    vestibular26: undefined,
    vestibular27: undefined,
    vestibular28: undefined,
    vestibular31: undefined,
    vestibular32: undefined,
    vestibular33: undefined,
    vestibular34: undefined,
    vestibular35: undefined,
    vestibular36: undefined,
    vestibular37: undefined,
    vestibular38: undefined,
    vestibular41: undefined,
    vestibular42: undefined,
    vestibular43: undefined,
    vestibular44: undefined,
    vestibular45: undefined,
    vestibular46: undefined,
    vestibular47: undefined,
    vestibular48: undefined,
  },
},
caras:[
    { value: 'oclusal', label: 'Oclusal' },
    { value: 'vestibular', label: 'Vestibular' },
    { value: 'incisal', label: 'Incisal' },
    { value: 'lingual', label: 'Lingual' },
    { value: 'mesial', label: 'Mesial' },
    { value: 'distal', label: 'Distal' },
  ],
  dientes: [
    { value: '11', label: 'Incisivo Central Superior Izquierdo' },
    { value: '12', label: 'Incisivo Lateral Superior Izquierdo' },
    { value: '13', label: 'Canino Superior Izquierdo' },
    { value: '14', label: 'Primer Premolar Superior Izquierdo' },
    { value: '15', label: 'Segundo Premolar Superior Izquierdo' },
    { value: '16', label: 'Primer Molar Superior Izquierdo' },
    { value: '17', label: 'Segundo Molar Superior Izquierdo' },
    { value: '18', label: 'Tercer Molar Superior Izquierdo' },
    { value: '21', label: 'Incisivo Central Superior Derecho' },
    { value: '22', label: 'Incisivo Lateral Superior Derecho' },
    { value: '23', label: 'Canino Superior Derecho' },
    { value: '24', label: 'Primer Premolar Superior Derecho' },
    { value: '25', label: 'Segundo Premolar Superior Derecho' },
    { value: '26', label: 'Primer Molar Superior Derecho' },
    { value: '27', label: 'Segundo Molar Superior Derecho' },
    { value: '28', label: 'Tercer Molar Superior Derecho' },
    { value: '31', label: 'Incisivo Central Inferior Izquierdo' },
    { value: '32', label: 'Incisivo Lateral Inferior Izquierdo' },
    { value: '33', label: 'Canino Inferior Izquierdo' },
    { value: '34', label: 'Primer Premolar Inferior Izquierdo' },
    { value: '35', label: 'Segundo Premolar Inferior Izquierdo' },
    { value: '36', label: 'Primer Molar Inferior Izquierdo' },
    { value: '37', label: 'Segundo Molar Inferior Izquierdo' },
    { value: '38', label: 'Tercer Molar Inferior Izquierdo' },
    { value: '41', label: 'Incisivo Central Inferior Derecho' },
    { value: '42', label: 'Incisivo Lateral Inferior Derecho' },
    { value: '43', label: 'Canino Inferior Derecho' },
    { value: '44', label: 'Primer Premolar Inferior Derecho' },
    { value: '45', label: 'Segundo Premolar Inferior Derecho' },
    { value: '46', label: 'Primer Molar Inferior Derecho' },
    { value: '47', label: 'Segundo Molar Inferior Derecho' },
    { value: '48', label: 'Tercer Molar Inferior Derecho' },
  ],
  estado: [
    { value: "#000000", label: 'caries' },
    { value: "#FFF633", label: 'corona' },
    { value: 0, label: 'ausente' },
    { value: 1, label: 'sano' },

  ]
})



export { state }
